[package]
name = "mage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
winit = "0.28.3"

[dev-dependencies]
color-eyre = "0.6.2"
